### ISSUE TITLE
Map out of sync

### ISSUE THREAD

**Issue by MyPeSePe** [meatlayer/ets2-mobile-route-advisor#14]
![bWXOSAGKQD](https://user-images.githubusercontent.com/101088538/156982693-7164417e-41df-46f8-87e5-6f2e834799ab.png)
![firefox_8dP4R7B1HL](https://user-images.githubusercontent.com/101088538/156982786-879224e9-4e28-45f2-93d8-98788170208c.png)
The map is out of sync with the game and the loadout name appears undefined

**Comment by meatlayer** [comment]
Hi.
Please tell me, you are any add-ons in the game? 
What version of server telemetry are you using? 
Please send your file: \Telemetry Server\Html\skins\ets2-mobile-route-advisor\maps\ets2\js\map.js here

**Comment by MyPeSePe** [comment]
Mods 
![imagen](https://user-images.githubusercontent.com/101088538/157280744-14c43837-58bc-4529-bd34-0e2250f089b5.png)
Version : your version
File : 
[map.zip](https://github.com/meatlayer/ets2-mobile-route-advisor/files/8207912/map.zip)


I already fixed the load name error, but it is not synchronized with the map

**Comment by MyPeSePe** [comment]
Work thx
