### ISSUE TITLE
Route Advisor nor detected

### ISSUE THREAD

**Issue by CassieOJ** [meatlayer/ets2-mobile-route-advisor#15]
Upon installation of server version 4.1.2.3, there was no detection of the Route Advisor. I have retried a few times now, and cannot get the Route Advisor to appear.

**Comment by meatlayer** [comment]
I just downloaded the telemetry server, inserted the skin, everything works unmistakably. Or the skin `ets2-mobile-route-advisor` is placed in wrong absolute path. Either the name of the `ets2-mobile-route-advisor` folder has an incorrect name. I advise you to read the installation instructions carefully. 

Again, even the standard skins that are preinstalled in the telemetry server should work. If they don't work, then Router Mobile Advisor skin won't work either.
