### ISSUE TITLE
Install Instructions not clear

### ISSUE THREAD

**Issue by geekmoto13** [meatlayer/ets2-mobile-route-advisor#19]
the second instruction isn't clear am i supposed to copy the 4.0.5 files into the normal release folder and overwrite the default version?

**Comment by meatlayer** [comment]
The whole point of the installation is to place the ets2-mobile-route-advisor folder with up-to-date files in the telemetry server, specifically, in the skins folder. If you previously had a folder of the old version of ets2-mobile-route-advisor there, just clear this folder and place the current files from version 4.0.5 in it.
The file placement structure is the same.
