### ISSUE TITLE
Promods is not available

### ISSUE THREAD

**Issue by kizule** [meatlayer/ets2-mobile-route-advisor#24]
Support for Promods should be added as well. The map isn't shown exactly as in the game, because I'm playing on TruckersMP with Promods.

**Comment by meatlayer** [comment]
Hi! At the moment, you can download the map for Promod via [4.0.7](https://github.com/meatlayer/ets2-mobile-route-advisor/releases/tag/v4.0.7) version, the archive name is [Additional_ets2_PROMOD-RUSMAP_v148.7z](https://github.com/meatlayer/ets2-mobile-route-advisor/releases/download/v4.0.7/Additional_ets2_PROMOD-RUSMAP_v148.7z)

**Comment by kizule** [comment]
Oh, great! But there are two config.json files, what I should do?

**Comment by meatlayer** [comment]
config.json is not required. 
The most important thing is the tiles and the js folder
Just replace everything

**Comment by kizule** [comment]
So I just have to extract the titles and the js folder in a mobile-advisor directory?

**Comment by meatlayer** [comment]
Yes, for reliability, you can even completely delete **tiles** and **js** in ets2-mobile-route-advisor and then unpack the tiles and js folders from the Promod archive to this place.

**Comment by kizule** [comment]
I tried that, but I'm still seeing an incorrect map (the usual map that doesn't include cities that are in Promods only, as well as cities that are having changes in Promods).

**Comment by meatlayer** [comment]
What if get version [4.0.6](https://github.com/meatlayer/ets2-mobile-route-advisor/releases/download/v4.0.6/Additional_ets2_PROMOD-RUSMAP.7z)? Is the situation similar?

**Comment by kizule** [comment]
It's not any better.

**Comment by meatlayer** [comment]
Promod added in ver [4.0.8 release](https://github.com/meatlayer/ets2-mobile-route-advisor/releases/tag/4.0.8) in a separate archive .7z
