### ISSUE TITLE
Canot get it to work

### ISSUE THREAD

**Issue by NigeUK** [meatlayer/ets2-mobile-route-advisor#25]
I'm sure that this dash is absolutely fabulous, but I can't get it to run.

1. Install Telemetry Server
2. Unzip route advisor to skins folder.
3. Start Telemetry server
4. Click on link to open Index.html
5. A list of the default dashes appear with images.
6. The Route advisor appears, but without an image.
7. Click the Route Advisor - "Failed to load dashboard.html for skin: ets2-mobile-route-advisor"
8. Click on any of the other dashes in the list and they run ok.
9. I have an older version of the telemetry server (3.2.5) and an older version of the Route Advisor. These don't have the same issue (the old route advisor doesn't have the correct maps, but it does run).

I've seen some of your answers to this issue previously. The folder structure I downloaded from here is read-only, so I'm not sure how the folder could be renamed and cause the dash not to work.
As I say, I admire the work you put into this, but something, somewhere isn't working as it should.

**Comment by NigeUK** [comment]
Update: Solved it by unzipping again, then moving the contents of the folder "ets2-mobile-route-advisor-4.0.8" to a folder called
"ets2-mobile-route-advisor"

**Comment by meatlayer** [comment]
I recorded a video instruction on how to easily install the "ets2-mobile-route-advisor" skin for the telemetry server.
If that doesn't help, then I'm afraid there's nothing else I can do.

[https://www.youtube.com/watch?v=XL5B5ffoGag](https://www.youtube.com/watch?v=XL5B5ffoGag)

**Comment by NigeUK** [comment]
Thanks. Yes. I watched your video. At the point where you rename the unzipped folder, I was getting an error. Anyhow, it's solved now,
Thank you for your hard work!
