### ISSUE TITLE
Missing Part of I80 (stock map)

### ISSUE THREAD

**Issue by WarLord211** [meatlayer/ets2-mobile-route-advisor#26]
I today i found a missing part of the Interstate 80 between Cheyenne (WY) and Sidney (NE).
The ramp in booth citys is there but nothing between.

Mobile version 4.0.9
![mobile](https://github.com/user-attachments/assets/56026238-2945-486c-9514-d471731965da)

ATS (stock map) 1.50
![Screenshot 2024-08-09 185644](https://github.com/user-attachments/assets/6ff000de-c59b-4696-980e-1a23925d4046)

Missing part
![mobile - Kopie](https://github.com/user-attachments/assets/c214c701-6b42-4d58-9e02-f35cd15a14e5)

**Comment by meatlayer** [comment]
Thank you for reporting this. I have uploaded the updated tiles, try to download and replace them for ATS

https://github.com/meatlayer/ets2-mobile-route-advisor/tree/master/maps/ats/tiles

This should solve the problem with the road display

**Comment by WarLord211** [comment]
Thx for the fix. Works for me
