### ISSUE TITLE
Missing Part of R77 (stock map)

### ISSUE THREAD

**Issue by WarLord211** [meatlayer/ets2-mobile-route-advisor#29]
I today i found a missing part of the Route 77 near Waco (TX).
Part of the street is missing in Advisor, in Game its there.

Mobile version 4.1.0
![Screenshot_20240921-233140](https://github.com/user-attachments/assets/1c9867e7-8f9b-4497-9362-1e5d87ff8e97)

ATS 1.51.2.7
![Screenshot 2024-09-21 233300](https://github.com/user-attachments/assets/72f02c7a-42cb-4e5b-ad40-a1268d82c9d5)
![Screenshot 2024-09-21 233300](https://github.com/user-attachments/assets/2194dcce-369d-46c2-80cd-bd51852d36ba)

**Comment by meatlayer** [comment]
There are problems with this section of road 77 in the game. 
This can be seen in the textures on my screenshot. And just at the intersection. I sent a bug report to the SCS forum.

![waco-road77](https://github.com/user-attachments/assets/5a737394-38af-4c84-a05c-7b2e2d11f82e)
