### ISSUE TITLE
Square after waiting for drive...

### ISSUE THREAD

**Issue by Sokoloft** [meatlayer/ets2-mobile-route-advisor#9]
As the title says. All I get is a square after waiting for drive... Picture below.

![atsra](https://user-images.githubusercontent.com/49052130/120091201-e4420b80-c0d6-11eb-946b-3afc256cf823.png)

Thanks.

**Comment by meatlayer** [comment]
Please run your current version of ETS2 Telemetry Server and click: Server - Uninstall in the program menu.
After that, completely delete the ETS2 Telemetry Server program by the shortcut uninstall.exe in the folder.
Next, download and install [Telemetry Server 4.1.2.3.exe](https://github.com/meatlayer/ets2-mobile-route-advisor/raw/master/Telemetry%20Server%20Setup%204.1.2.3.exe) upload the skin with the name of the **ets2-mobile-route-advisor** folder to the folder `\Documents\Telemetry Server\Html\skins\`

After that, start the Telemetry Server from the documents folder and check game login and map display.
If the problem persists, send the output of json data from the Telemetry Server URL: http://X.X.X.X:25555/api/ets2/telemetry

**Comment by Sokoloft** [comment]
Should note that I'm playing ATS on the current stable branch. Works on 3.6.0 and the 3.2.5 server but missing map data. I tried the steps you mentioned and still the same result.

Thanks.

`
{"game":{"connected":true,"gameName":"ATS","paused":true,"time":"0001-03-06T15:54:00Z","timeScale":3.0,"nextRestStopTime":"0001-01-01T07:23:00Z","version":"1.3","telemetryPluginVersion":"10","telemetryServerVersion":"4.1.2.3","maxTrailerCount":10},"truck":{"id":"autocar","make":"Autocar","model":" series DC","speed":0.00161095057,"cruiseControlSpeed":0.0,"cruiseControlOn":false,"odometer":3227.61084,"shifterType":"manual","forwardGears":15,"reverseGears":3,"gear":0,"displayedGear":0,"engineRpm":644.997742,"engineRpmMax":2350.0,"fuel":572.8369,"fuelCapacity":575.0,"fuelAverageConsumption":0.567587137,"fuelWarningFactor":0.15,"fuelWarningOn":false,"wearEngine":4E-06,"wearTransmission":4E-06,"wearCabin":0.0,"wearChassis":0.0,"wearWheels":4E-05,"userSteer":0.0,"userThrottle":0.0,"userBrake":0.0,"userClutch":0.0,"gameSteer":0.183431163,"gameThrottle":0.0,"gameBrake":0.0,"gameClutch":0.0,"engineOn":true,"electricOn":true,"wipersOn":false,"retarderBrake":0,"retarderStepCount":0,"parkBrakeOn":true,"motorBrakeOn":false,"brakeTemperature":31.9947224,"adblue":79.8918457,"adblueCapacity":80.0,"adblueAverageConsumption":0.0,"adblueWarningOn":false,"airPressure":105.7485,"airPressureWarningOn":false,"airPressureWarningValue":59.16,"airPressureEmergencyOn":false,"airPressureEmergencyValue":29.58,"oilTemperature":37.57484,"oilPressure":41.0283356,"oilPressureWarningOn":false,"oilPressureWarningValue":10.15,"waterTemperature":30.194006,"waterTemperatureWarningOn":false,"waterTemperatureWarningValue":105.0,"batteryVoltage":27.4295845,"batteryVoltageWarningOn":false,"batteryVoltageWarningValue":23.76,"lightsDashboardValue":0.75,"lightsDashboardOn":true,"blinkerLeftActive":false,"blinkerRightActive":false,"blinkerLeftOn":false,"blinkerRightOn":false,"lightsParkingOn":false,"lightsBeamLowOn":false,"lightsBeamHighOn":false,"lightsAuxFrontOn":false,"lightsAuxRoofOn":false,"lightsBeaconOn":false,"lightsBrakeOn":false,"lightsReverseOn":false,"placement":{"x":-80099.152847290039,"y":21.986228942871094,"z":-58946.732360839844,"heading":0.73249584436416626,"pitch":0.00087790691759437323,"roll":-8.1355137808714062E-05},"acceleration":{"x":-9.818004E-05,"y":-3.71748538E-05,"z":4.20087E-05},"head":{"x":-0.4276465,"y":-0.696720839,"z":1.070413},"cabin":{"x":0.0,"y":3.0,"z":-2.0},"hook":{"x":0.0,"y":0.9999998,"z":2.07587242},"licensePlate":".AEG-627","licensePlateCountryId":"new_mexico","licensePlateCountry":"New Mexico","wheelCount":6,"wheels":[{"simulated":true,"steerable":true,"powered":false,"liftable":false,"lifted":false,"radius":0.5434447,"position":{"x":-1.06886017,"y":0.506000161,"z":-2.6353333}},{"simulated":true,"steerable":true,"powered":false,"liftable":false,"lifted":false,"radius":0.5434447,"position":{"x":1.06886017,"y":0.506000161,"z":-2.6353333}},{"simulated":true,"steerable":false,"powered":true,"liftable":false,"lifted":false,"radius":0.5120085,"position":{"x":-0.9603542,"y":0.505999863,"z":1.25721788}},{"simulated":true,"steerable":false,"powered":true,"liftable":false,"lifted":false,"radius":0.5120085,"position":{"x":0.9603542,"y":0.505999863,"z":1.25721788}},{"simulated":true,"steerable":false,"powered":true,"liftable":false,"lifted":false,"radius":0.5120085,"position":{"x":-0.9603542,"y":0.5059998,"z":2.62224245}},{"simulated":true,"steerable":false,"powered":true,"liftable":false,"lifted":false,"radius":0.5120085,"position":{"x":0.9603542,"y":0.5059998,"z":2.62224245}}]},"shifter":{"type":"manual","forwardGears":15,"forwardGearNames":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"reverseGears":3,"reverseGearNames":["N","R1","R2","R3"],"differentialRatio":4.63,"forwardGearRatios":[11.69,7.83,8.96,6.0,6.92,4.63,5.33,3.57,4.19,2.8,2.19,1.68,1.3,1.0,0.78],"reverseGearRatios":[-11.54,-7.73,-2.16],"tyreCircumference":3.2170442100728334,"forwardSpeedAt1500Rpm":[0,5,8,7,10,9,14,12,18,15,22,29,37,48,63,80],"reverseSpeedAt1500Rpm":[0,-5,-8,-29],"forwardRpmAtCurrentSpeed":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"reverseRpmAtCurrentSpeed":[0,0,0,0],"selectorCount":1,"slotCount":1,"slots":[{"slot":0,"seletors":[{"selector":0,"gear":0,"gearName":null}]}],"gear":0,"displayedGear":0,"displayedGearName":null,"gearRatio":0.0,"slot":0,"selector":0,"bestGear":1,"bestGearName":null},"trailerCount":1,"trailers":[{"number":0,"attached":true,"present":true,"id":"vehicle.scs.flatbed","name":"A-PLO-18","wearWheels":2E-05,"wearChassis":2E-05,"wear":2E-05,"cargoDamage":0.0,"cargoAccessoryId":"","brandId":"scs","brand":"","bodyType":"flatbed","cargo":"flatbed","licensePlate":"83341","licensePlateCountry":"Oregon","licensePlateCountryId":"oregon","chainType":"single","placement":{"x":-80106.321105957031,"y":21.96375846862793,"z":-58948.620429992676,"heading":0.69986283779144287,"pitch":-0.00021670671412721276,"roll":0.00012172914284747094},"distance":7.41277552,"hook":{"x":0.0,"y":1.0,"z":-5.36210966},"wheelCount":4,"wheels":[{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":-0.924798131,"y":0.520000041,"z":5.09917164}},{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":0.924798131,"y":0.520000041,"z":5.09917164}},{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":-0.92449,"y":0.52,"z":6.48623753}},{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":0.92449,"y":0.52,"z":6.48623753}}]}],"trailer":{"number":0,"attached":true,"present":true,"id":"vehicle.scs.flatbed","name":"A-PLO-18","wearWheels":2E-05,"wearChassis":2E-05,"wear":2E-05,"cargoDamage":0.0,"cargoAccessoryId":"","brandId":"scs","brand":"","bodyType":"flatbed","cargo":"flatbed","licensePlate":"83341","licensePlateCountry":"Oregon","licensePlateCountryId":"oregon","chainType":"single","placement":{"x":-80106.321105957031,"y":21.96375846862793,"z":-58948.620429992676,"heading":0.69986283779144287,"pitch":-0.00021670671412721276,"roll":0.00012172914284747094},"distance":7.41277552,"hook":{"x":0.0,"y":1.0,"z":-5.36210966},"wheelCount":4,"wheels":[{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":-0.924798131,"y":0.520000041,"z":5.09917164}},{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":0.924798131,"y":0.520000041,"z":5.09917164}},{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":-0.92449,"y":0.52,"z":6.48623753}},{"simulated":true,"steerable":false,"powered":false,"liftable":false,"lifted":false,"radius":0.515,"position":{"x":0.92449,"y":0.52,"z":6.48623753}}]},"job":{"income":0,"deadlineTime":"0001-01-01T00:00:00Z","remainingTime":"0001-01-01T00:00:00Z","sourceCity":"","sourceCompany":"","destinationCity":"","destinationCompany":"","specialTransport":false,"jobMarket":""},"cargo":{"cargoLoaded":false,"cargoId":"","cargo":"","mass":0.0,"unitMass":0.0,"unitCount":0,"damage":0.0},"navigation":{"estimatedTime":"0001-01-01T00:00:00Z","estimatedDistance":0,"speedLimit":0},"finedEvent":{"fineOffense":"","fineAmount":0,"fined":false},"jobEvent":{"jobFinished":false,"jobCancelled":false,"jobDelivered":false,"cancelPenalty":0,"revenue":0,"earnedXp":0,"cargoDamage":0.0,"distance":0,"deliveryTime":"0001-01-01T00:00:00Z","autoparkUsed":false,"autoloadUsed":false},"tollgateEvent":{"tollgateUsed":false,"payAmount":0},"ferryEvent":{"ferryUsed":false,"sourceName":"","targetName":"","sourceId":"","targetId":"","payAmount":0},"trainEvent":{"trainUsed":false,"sourceName":"","targetName":"","sourceId":"","targetId":"","payAmount":0}}
`

**Comment by Sokoloft** [comment]
This is the output from 3.6.0 where the map works as intended. However the map data isn't updated for Colorado etc. Seems to me the newer version does something different to determine gears. 

Thanks. 

`
{"game":{"connected":true,"gameName":"ATS","paused":false,"time":"0001-03-06T16:37:00Z","timeScale":3.0,"nextRestStopTime":"0001-01-01T06:40:00Z","version":"1.3","telemetryPluginVersion":"9"},"truck":{"id":"autocar","make":"Autocar","model":" series DC","speed":0.002509068,"cruiseControlSpeed":0.0,"cruiseControlOn":false,"odometer":3232.66943,"gear":0,"displayedGear":5,"forwardGears":15,"reverseGears":3,"shifterType":"manual","engineRpm":644.997742,"engineRpmMax":2350.0,"fuel":569.344,"fuelCapacity":575.0,"fuelAverageConsumption":0.5677491,"fuelWarningFactor":0.15,"fuelWarningOn":false,"wearEngine":1.39999993E-05,"wearTransmission":1.39999993E-05,"wearCabin":0.0,"wearChassis":0.0,"wearWheels":0.000139999989,"userSteer":0.0,"userThrottle":0.0,"userBrake":0.0,"userClutch":0.0,"gameSteer":-0.486821741,"gameThrottle":0.0,"gameBrake":0.0,"gameClutch":1.0,"shifterSlot":0,"engineOn":true,"electricOn":true,"wipersOn":false,"retarderBrake":0,"retarderStepCount":0,"parkBrakeOn":true,"motorBrakeOn":false,"brakeTemperature":38.18234,"adblue":79.7172,"adblueCapacity":80.0,"adblueAverageConsumption":0.0,"adblueWarningOn":false,"airPressure":122.444847,"airPressureWarningOn":false,"airPressureWarningValue":59.16,"airPressureEmergencyOn":false,"airPressureEmergencyValue":29.58,"oilTemperature":45.89637,"oilPressure":41.0283356,"oilPressureWarningOn":false,"oilPressureWarningValue":10.15,"waterTemperature":32.3427467,"waterTemperatureWarningOn":false,"waterTemperatureWarningValue":105.0,"batteryVoltage":27.4295464,"batteryVoltageWarningOn":false,"batteryVoltageWarningValue":23.76,"lightsDashboardValue":0.75,"lightsDashboardOn":true,"blinkerLeftActive":false,"blinkerRightActive":false,"blinkerLeftOn":false,"blinkerRightOn":false,"lightsParkingOn":false,"lightsBeamLowOn":false,"lightsBeamHighOn":false,"lightsAuxFrontOn":false,"lightsAuxRoofOn":false,"lightsBeaconOn":false,"lightsBrakeOn":false,"lightsReverseOn":false,"placement":{"x":-48666.4336,"y":89.53876,"z":18023.5527,"heading":0.748593152,"pitch":-0.00445647072,"roll":-3.418889E-05},"acceleration":{"x":0.0002933522,"y":0.0009108047,"z":0.000121912992},"head":{"x":-0.4276465,"y":-0.696720839,"z":1.070413},"cabin":{"x":0.0,"y":3.0,"z":-2.0},"hook":{"x":0.0,"y":0.9999998,"z":2.07587242}},"trailer":{"attached":false,"id":"","name":"","mass":0.0,"wear":0.0,"placement":{"x":0.0,"y":0.0,"z":0.0,"heading":0.0,"pitch":0.0,"roll":0.0}},"job":{"income":0,"deadlineTime":"0001-01-01T00:00:00Z","remainingTime":"0001-01-01T00:00:00Z","sourceCity":"","sourceCompany":"","destinationCity":"","destinationCompany":""},"navigation":{"estimatedTime":"0001-01-01T00:00:00Z","estimatedDistance":0,"speedLimit":0}}
`

**Comment by meatlayer** [comment]
Yes, you are right, it is clearly in your non-standard truck. In telemetry, for some reason, incorrect values of the wear model are returned. Most likely, this is the problem.

In your telemetry:
```
      "wearEngine":4E-06,
      "wearTransmission":4E-06,
      "wearCabin":0.0,
      "wearChassis":0.0,
      "wearWheels":4E-05,
```

In my telemetry normal values:
```
      "wearEngine":0.0041086236,
      "wearTransmission":0.00247317436,
      "wearCabin":0.00654179743,
      "wearChassis":0.008177247,
      "wearWheels":0.00142658746,
```

Unfortunately I have never tested ets2-mobile-route-advisor with truck addons and mods. 
Most likely it is possible to fix and bypass it in javascript file dashboard.js in function getDamagePercentage, but I'm not sure yet that I can find enough free time for this. 
Send a link to your truck add-on. Maybe I can find the time to try and fix it some day.

**Comment by Sokoloft** [comment]
Truck [here](https://forum.scssoft.com/viewtopic.php?f=207&t=275163). I also use a patch made by a user thesimp found on [this](https://forum.scssoft.com/viewtopic.php?f=207&t=275163&sid=068bfbf5cdcd2cd7d8cfe7c64b5b2130&start=1730) page for the mod. In the load order they mention. I also have the sound mod too. I'm using the DC with the 444 motor and the 15 speed transmission. 

![20210529164919_1](https://user-images.githubusercontent.com/49052130/120122193-5701c400-c175-11eb-87e6-0153e9839581.jpg)


Thanks. Appreciate it.

**Comment by meatlayer** [comment]
Unfortunately, I couldn't fix this situation with the truck mod. 
As far as I found out, this is a bug of a newer version of Telemetry Server 4.1.2.3, because on some other skins in the same version of the server telemetry, the same problems.
